image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Angular.ng-template
    - streetsidesoftware.code-spell-checker
    - vscjava.vscode-java-pack
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
