version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=m0xai
      - POSTGRES_PASSWORD=1299
      - POSTGRES_DB=fertig_work
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U m0xai -d fertig_work' ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

# It's not easy to make live reload work
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fertig_work
  #     - SPRING_DATASOURCE_USERNAME=m0xai
  #     - SPRING_DATASOURCE_PASSWORD=1299
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   volumes:
  #     - './backend:/app/backend'
  #   depends_on:
  #     - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      # Don't use /usr/src/app/web/ because in Dockerfile it is /app/web
      - './web:/app/web'
      - '/app/web/node_modules'

volumes:
  db:
    driver: local
