version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=m0xai
      - POSTGRES_PASSWORD=1299
      - POSTGRES_DB=fertig_work
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U m0xai -d fertig_work' ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  # backend:
  #   build:
  #     context: ./backend
  #   volumes:
  #     - './backend:/usr/src/app/backend'

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      # Don't use /usr/src/app/web/ because in Dockerfile it is /app/web
      - './web:/app/web'
      - '/app/web/node_modules'

volumes:
  db:
    driver: local
